[project]
name = "python-playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.5",
    "more-itertools>=10.7.0",
    "numpy>=2.3.2",
]

[dependency-groups]
dev = [
    "ruff>=0.12.10",
    "watchfiles>=1.1.0",
]
